image_width: 1600
image_height: 1200
camera_name: right
distortion_model: plumb_bob
#comentarios considerando outputs Matlab
camera_matrix: # stereoParams.CameraParameters2.IntrinsicMatrix'
  rows: 3
  cols: 3
  data: [ 2685.5, 0.0, 792.71 ,
          0.0, 2681.6, 588.94  ,
         0.0, 0.0, 1.0]
distortion_coefficients: # stereoParams.CameraParameters2.RadialDistortion e stereoParams.CameraParameters2.TangentialDistortion
  rows: 1
  cols: 5
  data: [ -0.23929, 0.29649, 0.0010088, 0.0015038, -0.68318  ] # [k1, k2, t1, t2, k3]
rectification_matrix: # stereoParams.CameraParameters2.RotationMatrices(:,:,1)'
  rows: 3
  cols: 3
  data: [0.99244, -0.028408, 0.11943 ,
        0.028477, 0.99959, 0.0011265,
        -0.11942, 0.0022831, 0.99284 ]
projection_matrix: # Matriz intrinsica e stereoParams.CameraParameters2.TranslationVectors(1,:)
  rows: 3
  cols: 4
  data: [2685.5, 0.0, 792.71 , -146.34,
         0.0, 2681.6, 588.94 , -159.55,
         0.0, 0.0, 1.0, 1375.5]
