image_width: 4096
image_height: 3000
camera_name: left
camera_matrix:
  rows: 3
  cols: 3
  data: [8000.0, 0.0, 2048.0, 0.0, 8000.0, 1500.0, 0.0, 0.0, 1.0]
distortion_model: pinhole
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [8000.0, 0.0, 2048.0, 0.0, 0.0, 8000.0, 1500.0, 0.0, 0.0, 0.0, 1.0, 0.0]
