image_width: 1600
image_height: 1200
camera_name: right
distortion_model: plumb_bob
camera_matrix:
  rows: 3
  cols: 3
  data: [809.28,      0,       773.97,
            0 ,      808.22,       603.83,
            0,           0,            1]
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.0175,    0.0492,   -0.0244, 0.0010,   -0.0049]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.0000,    0.0022,   -0.0077,
   -0.0021,    0.9999,    0.0106,
    0.0077,   -0.0106,    0.9999]
projection_matrix:
  rows: 3
  cols: 4
  data: [1.0, 0.0, 0.0,-101.5949e-3,
         0.0, 1.0, 0.0, -0.9186e-3,
         0.0, 0.0, 1.0, -4.7364e-3]
