image_width: 1600
image_height: 1200
camera_name: left
distortion_model: plumb_bob
camera_matrix:
  rows: 3
  cols: 3
  data: [813.32, 0, 778.18,
         0, 812.37, 605.96,
         0, 0, 1]
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.055534, 0.11596, 0.0013919, -0.00079716, -0.059109]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1, 0, 0,
          0, 1, 0,
          0, 0, 1]  
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1, 0, 0, 0,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]