image_width: 2048
image_height: 2048
camera_name: left
camera_matrix:
  rows: 3
  cols: 3
  data: [4471.6, 0.0, 1033.7, 0.0, 4489.1, 1028.5, 0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.2518, 0.2871, 0.0006, 0.0002, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [4471.6, 0.0, 1033.7, 0.0, 0.0,  0.0, 4489.1, 1028.5, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 1
binning_y: 1
