image_width: 2448
image_height: 2048
camera_name: left
distortion_model: plumb_bob
camera_matrix:
  rows: 3
  cols: 3
  data: [1274.7, 0.0, 1245.2, 0.0, 1272.7, 1032.1, 0.0, 0.0, 1.0]

distortion_coefficients:
  rows: 1
  cols: 5
  data: [ -0.21279, 0.10013, -0.00014477, -4.2986e-05, -0.022903]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0,
         0, 1, 0,
         0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [1274.7, 0.0, 1245.2, 0.0, 0.0,  1272.7, 1032.1, 0.0, 0.0, 0.0, 1.0, 0.0]

